name: WiseCash Help
permalink: /:title
gems: ['jekyll-assets']
assets:
  js_compressor:  uglifier
  css_compressor: sass
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
